
  Ext.define('JBFacts.store.Users', {
      extend: 'Ext.data.Store',
      model: 'JBFacts.model.User',
      data: [
  
{fact: ' James Bond e racit si merge la farmacie. - As dori ceva de gat. Rosu in gat.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Va pot da doi. Patruzeci si doi.', author: 'Marius Petrescu', language: 'R'},
{fact: ' Va pot da ceva de sept. Faringosept.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Cu ce se plimba James Bond la mare? Cu bicicleta, hidro-bicicleta!', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond la restaurant comanda vacuta, ciorba de vacuta', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Ce poarta James Bond cand e soare? Glasses. Sunglasses.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Ce mananca James Bond la micul dejun? Praga, sunca de Praga.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Ce bicicleta prefera James Bond? Cursiera. Semi-cursiera.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' Ce a vazut James Bond la Praga? Ceara. Figuri de ceara. Muzeul Figurilor de Ceara.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Ce comanda James Bond la bar? O blonda, bere blonda.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Ce mancare ii face nevasta lui James Bond? Nevasta? Care nevasta?', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Ce caine prefera James Bond? German, dog german', author: 'Cornel Izbasa', language: 'R'},
{fact: ' In ce domeniu ar activa James Bond in Autosar Center? Management. Safety Management. Functional Safety Management. Coleg cu Simona', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Ce foloseste James Bond mult in Java? Collections. Garbage collections.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Ce foloseste James Bond mult in Java 8? Expressions. Lambda expressions.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Ce film cu karate ii place lui James Bond? Dragon. Hidden Dragon. Crouching Tiger Hidden Dragon. (STAAAHP MEEEE)', author: 'Cornel Izbasa', language: 'R'},
{fact: ' De ce nu i-a placut Drive lui James Bond? Scurt. Titlu scurt.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' De cine ii e frica lui James Bond? Norris. Chuck Norris.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Why doesn`t James Bond optimize his Java code? He relies on the compiler. Just-in-time compiler.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Ce spune James Bond cand pleaca de la club? Buna. Noapte buna.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Cum e James Bond dupa o zi lunga de lucru? Obosit, foarte obosit.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' What programming languages does James Bond prefer? Functional, purely functional.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' Ce asteapta James Bond cu nerabdare la inceputul lunii Mai? Vacanta, mini-vacanta.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' What is James Bond looking for in C code? Flows. Buffer overflows.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Off, Fuck off.', author: 'Marius Petrescu', language: 'E'},
{fact: ' Este ora 5, 7 fara 5.', author: 'Marius Petrescu', language: 'R'},
{fact: ' Which is James Bond`s favourite artistic movement? Modernism. Postmodernism.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' What`s James Bond`s desk job? Programming. Metaprogramming.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' And he likes bugging. Debugging.', author: 'Marius Petrescu', language: 'E'},
{fact: ' ...using an assembler. A disassembler.', author: 'Marius Petrescu', language: 'E'},
{fact: ' It`s all about engineering. Reverse engineering.', author: 'Marius Petrescu', language: 'E'},
{fact: ' JB has a crush for models. Meta-models.', author: 'Marius Petrescu', language: 'E'},
{fact: ' But he hates lines. Deadlines.', author: 'Marius Petrescu', language: 'E'},
{fact: '  My name is Bond, Vagabond:)))', author: 'Draghita Ciprian-ioan', language: 'E'},
{fact: ' What does James Bond prefer, compilers or interpreters? Interpreters. Circular interpreters. Meta-circular interpreters.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' What kind of languages does James Bond prefer? Iconic. Homoiconic.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Chuck Norris can type in a quine before it prints itself.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' What does James Bond use when he`s writing exploits? Sleds. NOP sleds.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond became a doctor so he could perform injections. SQL injections.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' What does James Bond like to play ? Birds. Angry Birds.', author: 'Adrian Valentin Dan', language: 'E'},
{fact: ' James Bond once took a fall. Skyfall.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Dan James bond gave him the finger. Goldfinger. How does James Bond like his pussy ? Octopussy. James bond once had something in his eye. Goldeneye. Are movie titles too easy ? No. Dr No,', author: 'Adrian Valentin', language: 'E'},
{fact: ' James Bond is walking this way. This highway.', author: 'Laura Pantis', language: 'E'},
{fact: ' What does James Bond provide? Service. Denial of service.', author: 'Laura Pantis', language: 'E'},
{fact: ' James Bond likes phones. IPhones.', author: 'Laura Pantis', language: 'E'},
{fact: ' James Bond travels free. Duty free.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' How does JB keep track of his actions? He has a log. A backlog.', author: 'Florina Craciunescu', language: 'E'},
{fact: ' What does JB do before taking his suit? He showers in the fall. The waterfall.', author: 'Florina Craciunescu', language: 'E'},
{fact: ' How does JB talk with his enemies? He uses mail. Blackmail.', author: 'Florina Craciunescu', language: 'E'},
{fact: ' What does JB`s GPS sound like? Turn left... second to the left.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Ce isi ia James Bond cand trece prin Romania? Vinieta, rovinieta.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond`s stance on religion? Theist. Atheist.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Once, James Bond wanted to switch from programming to testing. Penetration testing.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' For secure logins, James Bond uses SSH. OpenSSH.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' What made James Bond`s heart bleed? SSL. OpenSSL.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' When it comes to secure communication, James Bond likes privacy. Good privacy. Pretty Good Privacy.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' What`s annoying James Bond? Tracking. Backtracking.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond can read you like a book. Facebook.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond knows tomorrow dies. Never dies.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' How did JB`s kids figure out Santa isn`t real? He introduced himself as ``Claus. Santa Claus.``', author: 'Cornel Izbasa', language: 'E'},
{fact: ' What music is James Bond into? Rock. Hard Rock.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond likes wearing ties. Bow ties.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond`s favourite Asian dish? Soup. Noodle soup. Chinese noodle soup.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' What is James Bond`s car? Martin. Aston Martin.', author: 'Andi Caraghiaur', language: 'E'},
{fact: ' How did James Bond land the main role in Richard III? He killed the ``A horse, a horse, my kingdom for a horse!`` line.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond`s favourite wine? Corton. Aloxe Corton.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond`s favourite philosophy work? Human, All Too Human.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond`s favourite icon? Computer, My Computer.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' If James Bond finds a bug he enters a request. Change request.', author: 'Alexandru Bogdan', language: 'E'},
{fact: ' James Bond likes men. Women.', author: 'Alexandru Bogdan', language: 'E'},
{fact: ' James Bond likes UNIX, GNU. JB likes Jobs, BJs.', author: 'Ioan Tandau', language: 'E'},
{fact: ' JB likes bush, George Bush.', author: 'Ioan Tandau', language: 'E'},
{fact: ' JB likes Dick, Philip K. Dick.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is mental, sentimental.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is enjoying himself on a cruise. Tom Cruise.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond wants to have a baby. Hasta la vista, baby.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond enjoys travel, time travel.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond follows one script, JavaScript.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond likes working. Networking.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes dislikes.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond likes spears, Britney Spears.', author: 'Alexandru Bogdan', language: 'E'},
{fact: ' James Bond hates the Stones, kidney stones.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond likes trips, acid... erm, road trips.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Edits, erm edits!', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond is a hero, superhero.', author: 'Alexandru Bogdan', language: 'E'},
{fact: ' James Bond likes Lost. Paradise Lost.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes bridges, Jeff Bridges.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond writes comments. Facebook comments.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond once had pox, chicken pox.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond has a phobia, arachnophobia.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' Cand ceva nu merge in Windows, JB da start. Restart.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' When it`s cold, James Bond gets bumps, goosebumps.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond likes sets, querysets.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond likes blue, navy blue.', author: 'Gratiela Ghergu', language: 'E'},
{fact: 'James Bond has comments. 100 comments.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes phonies, symphonies.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' JB likes dalmatians, 101 dalmatians.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' JB reads Kafka. Franz Kafka.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond has left the building. Team-building.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is in team bulding at bai, Gioagiu Bai.', author: 'Alexandru Bogdan', language: 'E'},
{fact: ' James Bond flies with Hansa, Lufthansa.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Noi in TB suntem OK, not ok.', author: 'Guran Alin', language: 'R'},
{fact: ' When James Bond has to configure Autosar, he uses CT. CESSAR-CT.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond has needs. Service needs. And he loves good service. Room service.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' When in a coding emergency, James Bond turns to the sources. The resources.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' When programming, James Bond uses lots of strings. G-strings. So he relied on the buffer. The StringBuffer. Until he found out about the builder. The StringBuilder. Because his code was threaded. Single-threaded.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Cornel...shit...Greshit....', author: 'Ciobotea Catalin-Bogdan', language: 'R'},
{fact: ' Bine ca nu e ros. Puturos.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Cand ajunge in port, aeroport, James Bond mananca nitel, snitel, apoi ia leul, troleul, fiindca vai, n-are tramvai si nu-i place sa conteze, deconteze. Asa ca merge cu un general, abonament general.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Gutten tag. Samstag.', author: 'Cornel Izbasa', language: 'G'},
{fact: ' James Bond is tired. Retired.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes bacon. Kevin, haha no, Francis Bacon.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Cum i se adreseaza James Bond iubitei? Draga, draga draga.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' Lui James Bond ii place sa citeze. Resusciteze.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Lui James Bond ii place Argo. Cargo.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond has his own style. Lifestyle. Alternative lifestyle.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes Bach. Mönchengladbach. Borussia Mönchengladbach.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes it on top. Cherry on top.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' La ultimele se simtea aura. Laura.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond se bazeaza pe abilitati. Probabilitati.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' JB meets gay. Serghey. (E greu de scris. De nedescris. )', author: 'Marius Petrescu', language: 'R'},
{fact: ' James Bond when breaking-up: This is the end. My only friend, the end.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond to his enemy spy sweetheart: We`ll always have green. Paris Green.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' And he likes to use spray. Pepper spray.', author: 'Marius Petrescu', language: 'E'},
{fact: ' Chili pepper spray. Hot chili pepper spray. Red hot chili pepper spray.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is a fan of pistols. Sex Pistols.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' What an Ass. Pain in the ass.', author: 'Marius Petrescu', language: 'E'},
{fact: ' James Bond prefera sa fie platit cash. Pesches.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Once, James Bond got hurt. William Hurt.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond are un tic. Nevrotic.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond likes to give back. Feedback.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond has many ships. Relationships.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond has many friends. Girlfriends.', author: 'Litra Eros', language: 'E'},
{fact: ' James Bond has many boots. Reboots.', author: 'Litra Eros', language: 'E'},
{fact: ' James Bond successfully fulfils all his missions. Omissions.', author: 'Litra Eros', language: 'E'},
{fact: ' James Bond likes to ratify. Gratify.', author: 'Litra Eros', language: 'E'},
{fact: ' Lui James Bond îi place sa coteze. Tricoteze.', author: 'Litra Eros', language: 'R'},
{fact: ' Lui James Bond îi place orice colaj. Bricolaj.', author: 'Litra Eros', language: 'R'},
{fact: ' James Bond has IDEAS. No IDEAS.', author: 'Litra Eros', language: 'E'},
{fact: ' James Bond apreciaza supunerea. Presupunerea.', author: 'Litra Eros', language: 'R'},
{fact: ' Did u see the movie Volver, Revolver!', author: 'Draghita Ciprian-ioan', language: 'E'},
{fact: ' James Bond likes the Man. Burning Man.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes stockings. Bluestockings. [http://en.wikipedia.org/wiki/Bluestocking]', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond has been through lots of antics. Romantics.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes a special berry. Burberry.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes to edit, reddit', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond likes turkey, Turkey!', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond isi schimba casa. Carcasa.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond s-a dus la market, supermarket, a luat apa, ceapa si-acum e pe val, cascaval, apoi cauta mere, himere, daca nu-i ies in cale portocale.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond likes to mate, decimate.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond la lucru se confrunta cu multa negatie. Abnegatie.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond is hard, hardly.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond comments turn to verse. Perverse.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is always chasing tail. Cocktail.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is tolerant, intolerant.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond got his cat fixed. Prefixed.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond e invatat cu oile. Ploile.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond dodges bees. Frisbees.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond lucreaza cu sila. Ustensila.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond took a seat, a backseat, at the session, feedback session.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Why does James Bond love EMF? The prefix, the e_ prefix.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' When James Bond had to choose a server, an app server, he went with the cat, Tomcat, then upgraded to the Boss, JBoss.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is hoypxic, dyslexic', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond a pierdut o luna. Aluna.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond are un unchi. Manunchi.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond was looking for Dick, Moby Dick, but instead he found Riddick, Chronicles of Riddick.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond cauta rima. Crima.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' What`s easier than negation? Abnegation. Especially if you`re on the verge. To diverge. http://www.imdb.com/title/tt1840309/', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond drinks his vodka with lots of ice. Spice.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' This thread is ending. Neverending.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes men, fremen.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond likes his thread to end, append.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Queue O(1)s on both end of a queue, deque.', author: 'Ioan Tandau', language: 'E'},
{fact: ' Lui James Bond ii place Ana. Lesbiana.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond is a collector, garbage collector.', author: 'Ioan Tandau', language: 'E'},
{fact: ' That was before. Done before.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' That was done ready. Already.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' When dealing with concurrency, James Bond used locks, spinlocks. Nowadays he plays with mutexes, userspace mutexes, fast userspace mutexes, futexes.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Lately, James Bond had to deal with plenty of injections. Dependency injections. It made him lose control. Inversion of control.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is a controller, MVC.', author: 'Ioan Tandau', language: 'E'},
{fact: ' How many comments in the thread? Four. One hundred and ninety four.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Now we just need six. Six hundred and sixty six.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond lost his voice. Invoice.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond likes 6, 6-6-6 the number of the beast/hell and fire was spawned to be released', author: 'Ioan Tandau', language: 'E'},
{fact: ' Because James Bond listens to his maiden, Iron Maiden', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond likes Gauss, degaus', author: 'Ioan Tandau', language: 'E'},
{fact: ' Again, we got comments. 200 comments', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes an ass, a NAS', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond a primit un dar. Bondar.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond has hundred comments, 2 hundred', author: 'Alexandru Bogdan', language: 'E'},
{fact: ' 7 comments, 007 comments', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond cere bon. Jambon.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' 0014, because I`m twice as good as James Bond (http://www.imdb.com/title/tt1130080/)', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond errs, stderrs', author: 'Ioan Tandau', language: 'E'},
{fact: ' Nelu, you gotta let go, never let go.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes FM, RTFM', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond likes F.M., Dostoevsky F. M.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond nu gaseste nici un tel. Taitel.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond lets go, vertigo', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond likes cock. Hitchcock.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes TeX, LaTeX', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond likes LaTeX, latex', author: 'Ioan Tandau', language: 'E'},
{fact: ' Yeah, he loves the port by Lamport.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond ridica tava. Octava', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond is showing signs of sanity. Insanity.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes a system, a document preparation system.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond likes a short introduction to LaTeX, a not so short introduction to LaTeX.', author: 'Ioan Tandau', language: 'E'},
{fact: ' And he loves programming, literate programming.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' He loves literate programming, illiterate programming.', author: 'Ioan Tandau', language: 'E'},
{fact: ' He likes Weave, CWeave, and Tangle, CTangle.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond merge la mare, Baia Mare.', author: 'Marius Lucian Caciulescu', language: 'R'},
{fact: ' James Bond searches for pair. Au pair.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond loves the good book, The TeXbook.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond loves the Bible, the C Bible', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond heard of Putin, Rasputin, Grigori Rasputin', author: 'Marius Lucian Caciulescu', language: 'E'},
{fact: ' So he said, ``Russians... Oh those Russians!``', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond will have to create a site with facts. James Bond facts.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond loves Russians, Prussians.', author: 'Ioan Tandau', language: 'E'},
{fact: ' But he prefers aliens, Australians.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond drives a saucer, flying saucer.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond se intoarce de la alimentara plin de zel. Mezel.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond likes bars, Snickers bars.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond is a saucier, a great saucier http://en.wikipedia.org/wiki/Apocalypse_Now', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond plays roulette, Russian roulette.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond vede zeul. Muzeul.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond lives in a kingdom. United Kingdom.', author: 'Marius Lucian Caciulescu', language: 'E'},
{fact: ' James Bond come of age? Bondage.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' JB likes the shake. Milkshake. Strawberry milkshake.', author: 'Florina Craciunescu', language: 'E'},
{fact: ' James Bond rests in bath. Sabbath.', author: 'Marius Lucian Caciulescu', language: 'E'},
{fact: ' JB loves the madness. Fanta madness.', author: 'Florina Craciunescu', language: 'E'},
{fact: ' It`s good to be the king. Stephen Hawking.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond enjoys the fly. Firefly.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' When at parties, James Bond brings nades. Lemonades. Cause he`s got all the keys. Whiskeys. He works great as a host. Localhost.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes tin, Rin Tin Tin.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond spells, misspells.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond got sign. Design.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' To do is to be, to be is to do, do-bee do-bee-doo.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is caught in a net. Brunet.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' This thread is turning into a hole. A black hole.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' There`s nothing to see beyond the horizon, the event horizon.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond love his jet, astrophysical jet.', author: 'Ioan Tandau', language: 'E'},
{fact: ' Unless it`s another kind of hole, a worm hole.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond listens to his disc, his accretion disc.', author: 'Ioan Tandau', language: 'E'},
{fact: ' From which you can travel through time, space-time', author: 'Marius Lucian Caciulescu', language: 'E'},
{fact: ' James Bond goes with the flow, the bipolar outflow.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond lost the main role in 300. He kept saying: ``Sparta. This is SPARTAAAAA!!!``', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is waiting for the next cue. Rescue.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' Cause it`s a continuum, a space-time continuum.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' This thread, just like this thread.', author: 'Ioan Tandau', language: 'E'},
{fact: ' And then Bang! Big Bang.', author: 'Marius Lucian Caciulescu', language: 'E'},
{fact: ' James Bond vrea o tura. Prajitura.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond o face lata, ciocolata', author: 'Marius Lucian Caciulescu', language: 'R'},
{fact: ' James Bond goes for a ride. Upstairs for a ride. ', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond loves comics. Logicomix.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond e preocupat de probleme logice. Ecologice.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is tall. Continental', author: 'Marius Lucian Caciulescu', language: 'E'},
{fact: ' James Bond likes ham, Statham, and he drives a diesel, Vin Diesel.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes grass, bluegrass.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond follows a map, bitmap', author: 'Marius Lucian Caciulescu', language: 'E'},
{fact: ' James Bond doesn`t rot. Buddhabrot.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond rastoarna calul. Pocalul.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond likes n/2, (3n+1)/2.', author: 'Ioan Tandau', language: 'E'},
{fact: ' He`s following the rail. To the Grail. The Holy Grail.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes the conjecture, the Collatz conjecture.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Using a code, The Da Vinci Code.', author: 'Marius Lucian Caciulescu', language: 'E'},
{fact: ' James Bond solved the Collatz conjecture, dissolved.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond hopes to optimize his EMF application using some kind of query. IncQuery. EMF IncQuery.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond plateste o cota. Cocota.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond uses clips, Eclipse.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond likes to roll. Rock`n roll.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond rules, defrules.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond has a lisp, GC Lisp', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond are o tara. Chitara.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond loves to log, Prolog', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond`s girl plays with a stick. Lipstick.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' If they tried to accuse James Bond of a crime, it would never stick. Slapstick.', author: 'Cornel Izbasa', language: 'E'},
{fact: 'James Bond broke up with the ex, OS X.', author: 'Ioan Tandau', language: 'E'},
{fact: ' And again, we just need six. Six hundred and sixty six', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond sees the end, the weekend.', author: 'Ioan Tandau', language: 'E'},
{fact: ' And is looking forward to the night, the fortnight.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Home, go home!', author: 'Ioan Tandau', language: 'E'},
{fact: ' Like a pigeon? A homing pigeon?', author: 'Cornel Izbasa', language: 'E'},
{fact: ' What is JB`s favourite workout? He fights a man. A snowman.', author: 'Florina Craciunescu', language: 'E'},
{fact: ' No, like a ONE, a 127.0.0.1', author: 'Ioan Tandau', language: 'E'},
{fact: ' @Florina, with a thrower. A flamethrower.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Cum face James Bond cand se gadila? Hi! Hi, hi!', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond likes Romeo, Alfa Romeo.', author: 'Ioan Tandau', language: 'E'},
{fact: ' At home James Bond uses hat. Redhat.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond knows The Importance of Being a Nest. Earnest.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' He uses it too. Ubuntu.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' When he saw the S, Model S, Tesla Model S, James Bond said: ``Mine, all mine!``', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Ii place untu`, Ubuntu, dar ii displace Ina, margarina.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond`s favorite Tolkien quote? ``A hit. A fine hit.``', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond plange in vana. Savana.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond had a brother. A Big Brother.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes dot. Herodot.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' Of course he does, it`s part of Viz. GraphViz.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond are probleme cu fierea. Cartografierea.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' JB prefers tiles, tactiles.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond likes chains. Markov chains.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond needs a robe. A wardrobe.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond used to go out with the Saint. Silvia Saint. But now he`s more into Asians. Indonesians.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond knows a wash is urgent. Detergent.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond dislikes being tracked. Sidetracked.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond used to play Warcraft. World of Warcraft. Till he changed his craft. To Starcraft.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' When he won`t be paid in cash, James Bond will ask for a cheque. A rain check.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes many nations. Polynesians.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes Asia. Euthanasia. (thanks, Ali G.)', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond saw Django Chained. Unchained. Then he moved on to Bill. Kill Bill.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' From Asia he likes Stan, Kazakhstan.', author: 'Marius Lucian Caciulescu', language: 'E'},
{fact: ' Especially a rat, Borat', author: 'Marius Lucian Caciulescu', language: 'E'},
{fact: ' James Bond once joined a club. Fight club. But he couldn`t stand the pit. Brad Pitt.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Qui est-ce jolie? Angelina Jolie.', author: 'Marius Lucian Caciulescu', language: 'E'},
{fact: ' James Bond lost the main role in La vita è bella cause he kept saying ``La chiave! Maria, la chiave!``', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes using a wiki. Mediawiki. And he likes the Foundation. The Wikimedia Foundation.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' When playing MMOs, James Bond gets a lot of quests. Requests. Friend requests.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond wishes you a nice day. Mayday!', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes nails. Nine Inch Nails.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond loves his dog. Ghost Dog.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond loves playing. Role-playing. Most of all he likes being a rogue. Balrog.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond dislikes greed. Agreed. He`d rather have science. Conscience.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond once dated Aphrodite. Hermaphrodite.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond hates spikes. Lag spikes.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond`s favorite WoW class? Hunter, cause he uses Bond, Spirit Bond.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond are probleme cu gazul. Aragazul.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond`s favorite WoW race? Man, human.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James bond`s favorite game. Warcraft. World of Warcraft.', author: 'Adrian Valentin Dan', language: 'R'},
{fact: ' James Bond likes crafting. Minecrafting', author: 'Adrian Valentin Dan', language: 'E'},
{fact: ' James Bond lost the main role in the The Ring cause he kept saying ``Days. Seven days.``', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond`s favorite Asian philosophy book? Ching. Te Ching. Tao Te Ching.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond cauta un suc. Bursuc.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' Ce zice James Bond de o gluma de aici? Gutza. Dragutza. Da` ar trebui sa faceti ceva. Altceva.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond nu intra-n lac fara colac. Lucreaza pe un doc. Bondoc.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond`s ancestors were gatherers. Hunter-gatherers.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond cauta piciul. Lipiciul.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond l-a gasit pe piciu. Machu Picchu.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' De acolo merge spre ..., Titicaca.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Depinde cat e de mic piciu.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' Si daca are cu ce. Scutece.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Lui James Bond ii place Lia. Ciocarlia. Lia Ciocarlia.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond iubeste sarea. Nepasarea.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond are-o nana. Banana.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond is on your side. Inside.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond ingrijeste-o nara. Pensionara.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' O desfunda cu roi. Usturoi.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Furnicile lui James Bond merg in roi. Musuroi.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' This James Bond thing is cute. Acute.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Geanta, James Bond a luat-o pe lei. Ulei.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' Si-acum trece printre dale. Pedale.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond keeps a log. Blog. Web blog.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' Thread-ul asta deja doare. Candoare.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Lui James Bond ii place lama. Dalai Lama.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond e plin de fler. Knopfler.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond simte fumul. Parfumul.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond are o viziune vasta. Nevasta.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond a auzit de-un tip vestit. Travestit.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond e campion la tir. Martir.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond has entered a new league. Colleague.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is working on a roof. Proof.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond wants to dance. Cha, cha-cha, cha-cha-cha.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond trage cu tunul. Tutunul.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond has an old sore. Dinosaur.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' The dinosaur was sick. In Jurassic.', author: 'Marius Lucian Caciulescu', language: 'E'},
{fact: ' Ce zice James Bond cand e obosit? Dorm. Adorm.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Cand e nervos, pe JB il supara macul. Stomacul.', author: 'Florina Craciunescu', language: 'R'},
{fact: ' Ce prefera James Bond? Afine. Transformarile afine.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Ce ii daruieste JB prietenei in verile calduroase? Rochite roase. Vaporoase.', author: 'Florina Craciunescu', language: 'R'},
{fact: ' Numai de-ar veni. Reveni.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' O vara cu gust. In august.', author: 'Marius Lucian Caciulescu', language: 'R'},
{fact: ' James Bond participa la niste scene. Obscene.', author: 'Gratiela Ghergu', language: 'R'},
{fact: ' James Bond doesn`t like codes. Prefix-free codes. He hates Huffman. David Huffman.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Ai scris sa vada toata lumea? Ca lumea', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Comentarii...sute. 400', author: 'Marius Lucian Caciulescu', language: 'R'},
{fact: ' Haha, ce numar. Fara numar.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' In Tunis James Bond ate cush. Cush cush.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' Who is James Bonds cousin ? Knows. Nobody knows.', author: 'Andi Caraghiaur', language: 'E'},
{fact: ' How many kids does James Bond have? One. Twenty one.', author: 'Andi Caraghiaur', language: 'E'},
{fact: ' What does James Bond`s lover say when she climaxes? Seven... Oh-ooh-seveen!!', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Cate carti de-ale lui Eliade mai are de citit James Bond? Trei. Maitreyi.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond loved his sister. They had a ``special`` Bond.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond e din Sebes. Caransebes.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' E vecin cu Dan, Bogdan.', author: 'Marius Lucian Caciulescu', language: 'R'},
{fact: ' Are un catel cu gri. Pedigree.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond wanted to join the legion. Religion. But then he changed his mind. Nevermind.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond, covalent bond.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond wants to search, research.', author: 'Ioan Tandau', language: 'E'},
{fact: ' Done, not done.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond`s a ten, rotten.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond saw yesterday at work a great actor. Tractor.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Double-take: James Bond likes his seat, shit. (http://imgur.com/0Czes)', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond writes his music in the pond. LilyPond.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond likes Mercury, Freddie Mercury.', author: 'Ioan Tandau', language: 'E'},
{fact: ' Bond, James Bond. Gay, Sergey.', author: 'Ioan Tandau', language: 'E'},
{fact: ' James Bond is shit, the shit.', author: 'Alexandru Bogdan', language: 'E'},
{fact: ' Wanna reach 500 comments?? Because that`s how you reach 500 coments.', author: 'Ivan Vazquez', language: 'E'},
{fact: ' Haha wanna get Archer references? Cause that`s how you get Archer references.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' 500? Pffft. Not unless we run out of people and ideas, right guys?! Guys?! Hey!?!!?', author: 'Ioan Tandau', language: 'E'},
{fact: ' Sunt cam multe comentarii de grijit. Ingrijit. Many comments to tend to. Attend to.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond demands comments, 500 comments.', author: 'Ivan Vazquez', language: 'E'},
{fact: ' James Bond has requests.. friend requests... unfriend requests.', author: 'Marius Petrescu', language: 'E'},
{fact: ' James Bond leaves no witnesses. Jehovah`s witnesses.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Tare, foarte tare.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond is a little tense. Intense.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond liked Vietnam. Good Morning, Vietnam.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond has a small fee. Coffee.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond is aggressive. Passive aggressive.', author: 'Gratiela Ghergu', language: 'E'},
{fact: ' James Bond mananca cu Gutza. Mamaliguta.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond is amazed: Christ, Jesus Christ!', author: 'Cornel Izbasa', language: 'E'},
{fact: ' James Bond enjoys a liver. Believer.', author: 'Cornel Izbasa', language: 'E'},
{fact: ' Lui James Bond ii place ceatza. Dulceatza.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' James Bond e de efect. Defect.', author: 'Cornel Izbasa', language: 'R'},
{fact: ' Fain ``pile``-ul. Poti face un top cu ``Cei mai plictisiti oameni din lume``! :))', author: 'Alecu', language: 'R'},
{fact: ' Cei mai plictisiti din lume. Glume. :)', author: 'Cornel Izbasa', language: 'R'},

      ]
  });
  
